# Generated by Django 3.1 on 2021-02-09 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoConsulta',
            fields=[
                ('id_motivo', models.AutoField(primary_key=True, serialize=False)),
                ('motivo_consulta', models.CharField(max_length=45)),
                ('descripcion_problema', models.CharField(max_length=45)),
                ('paso_algo_antes', models.BooleanField()),
                ('que_paso', models.CharField(max_length=45)),
                ('fecha_consulta', models.DateField()),
                ('alta_consulta', models.BooleanField()),
                ('archivo_consulta', models.BooleanField()),
            ],
            options={
                'db_table': 'motivo_consulta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoPrueba',
            fields=[
                ('id_tipo_prueba', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_prueba', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'tipo_prueba',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RegistroXMotivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_motivo', models.ForeignKey(db_column='id_motivo', on_delete=django.db.models.deletion.CASCADE, to='cita.motivoconsulta')),
                ('id_paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
            options={
                'db_table': 'registro_x_motivo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id_diagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
                ('fecha_diagnostico', models.DateField()),
                ('motivo_consulta', models.ForeignKey(db_column='motivo_consulta', on_delete=django.db.models.deletion.CASCADE, to='cita.motivoconsulta')),
            ],
            options={
                'db_table': 'diagnostico',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EvaluacionesAdministradas',
            fields=[
                ('id_prueba', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_administracion', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('id_motivo', models.ForeignKey(db_column='id_motivo', on_delete=django.db.models.deletion.CASCADE, to='cita.motivoconsulta')),
                ('id_tipo_prueba', models.ForeignKey(db_column='id_tipo_prueba', on_delete=django.db.models.deletion.CASCADE, to='cita.tipoprueba')),
            ],
            options={
                'db_table': 'evaluaciones_administradas',
                'managed': True,
                'unique_together': {('id_prueba', 'id_tipo_prueba', 'id_motivo')},
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cita', models.DateField()),
                ('realizada', models.BooleanField()),
                ('descripcion', models.CharField(max_length=45)),
                ('otros_indicacodres', models.CharField(max_length=45)),
                ('sugerencias', models.CharField(max_length=45)),
                ('motivo_consulta', models.CharField(max_length=45)),
                ('tareas_proxima_cita', models.CharField(max_length=45)),
                ('id_diagnostico', models.ForeignKey(db_column='id_diagnostico', on_delete=django.db.models.deletion.CASCADE, to='cita.diagnostico')),
                ('id_motivo', models.ForeignKey(db_column='id_motivo', on_delete=django.db.models.deletion.CASCADE, to='cita.motivoconsulta')),
            ],
            options={
                'db_table': 'cita',
                'managed': True,
                'unique_together': {('id_cita', 'id_diagnostico', 'id_motivo')},
            },
        ),
    ]
