# Generated by Django 3.1 on 2021-02-08 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id_estado_civil', models.AutoField(primary_key=True, serialize=False)),
                ('estado_civil', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'estado_civil',
            },
        ),
        migrations.CreateModel(
            name='NumeroContacto',
            fields=[
                ('id_numeros_de_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('numero_contacto', models.CharField(max_length=45)),
                ('nombre_contacto', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'numero_contacto',
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id_religion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_religion', models.CharField(max_length=45)),
                ('direccion_congregacion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'religion',
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id_sexo', models.AutoField(primary_key=True, serialize=False)),
                ('sexo', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'sexo',
            },
        ),
        migrations.CreateModel(
            name='TipoFamiliar',
            fields=[
                ('id_tipo_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_familiar', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipo_familiar',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('fecha_nacimiento', models.DateField()),
                ('departamento', models.CharField(max_length=45)),
                ('municipio', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('id_estado_civil', models.ForeignKey(db_column='id_estado_civil', on_delete=django.db.models.deletion.CASCADE, to='paciente.estadocivil')),
                ('id_numero_contacto', models.ForeignKey(db_column='id_numero_contacto', on_delete=django.db.models.deletion.CASCADE, to='paciente.numerocontacto')),
                ('id_religion', models.ForeignKey(db_column='id_religion', on_delete=django.db.models.deletion.CASCADE, to='paciente.religion')),
                ('id_sexo', models.ForeignKey(db_column='id_sexo', on_delete=django.db.models.deletion.CASCADE, to='paciente.sexo')),
            ],
            options={
                'db_table': 'paciente',
                'unique_together': {('id_paciente', 'id_numero_contacto', 'id_religion', 'id_estado_civil', 'id_sexo')},
            },
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('trato', models.TextField(max_length=45)),
                ('vives_con_el', models.BooleanField()),
                ('ocupacion', models.CharField(blank=True, max_length=45, null=True)),
                ('responsable', models.BooleanField()),
                ('id_paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
                ('id_tipo_familiar', models.ForeignKey(db_column='id_tipo_familiar', on_delete=django.db.models.deletion.CASCADE, to='paciente.tipofamiliar')),
            ],
            options={
                'db_table': 'familiar',
                'unique_together': {('id_familiar', 'id_paciente', 'id_tipo_familiar')},
            },
        ),
        migrations.CreateModel(
            name='DatosClinicos',
            fields=[
                ('id_datos_clinicos', models.AutoField(primary_key=True, serialize=False)),
                ('enfermedad', models.BooleanField()),
                ('nombre_enfermedad', models.CharField(max_length=45)),
                ('medicamento', models.CharField(max_length=45)),
                ('tratamiento_previo', models.BooleanField()),
                ('por_que_no_tratamiento', models.CharField(blank=True, max_length=45, null=True)),
                ('motivo', models.CharField(max_length=45)),
                ('periodo', models.CharField(max_length=45)),
                ('alta_antes', models.BooleanField()),
                ('alta_por_que_no', models.CharField(blank=True, max_length=45, null=True)),
                ('id_paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente')),
            ],
            options={
                'db_table': 'datos_clinicos',
                'unique_together': {('id_datos_clinicos', 'id_paciente')},
            },
        ),
    ]
